title: Telcomate Blog
description: A blog about telecommunications and technology
url: "https://telcomate.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .claude/

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/